# Generated by Django 3.1.5 on 2021-01-31 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1)),
                ('isInfected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportInfect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.TextField()),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.survivor')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('survivor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.survivor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.PositiveSmallIntegerField(default=0)),
                ('food', models.PositiveSmallIntegerField(default=0)),
                ('medication', models.PositiveSmallIntegerField(default=0)),
                ('ammunition', models.PositiveSmallIntegerField(default=0)),
                ('survivor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.survivor')),
            ],
        ),
    ]
